# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('taluka', models.CharField(max_length=30)),
                ('district', models.CharField(max_length=30)),
                ('message', models.TextField(blank=True, null=True)),
                ('mobile_no', models.CharField(max_length=10, verbose_name='mobile phone')),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
            ],
            options={
                'verbose_name': 'profile',
                'verbose_name_plural': 'profiles',
            },
        ),
    ]
